### ISSUE TITLE
Creating a channel inside the loop?

### ISSUE THREAD

**Issue by ghost** [gophercises/quiz#112]
Firstly thanks for creating these screencasts and making it public. 
In the quiz exercise, Problem #2, I see that a channel is being created on every iteration, is that required? As I can create the channel outside the loop as well. 

https://github.com/gophercises/quiz/blob/3b2250f3d56e07dd320f5c6272febe7827988d3e/main.go#L34

**Comment by joncalhoun** [comment]
You should be able to write a solution where the channel is created outside the loop. Not sure what you had in mind, and truthfully I don't have the time or capacity to review code & questions from this course at this time.
