### ISSUE TITLE
Incorrect problem.csv link on Quiz mainpage 

### ISSUE THREAD

**Issue by hrmnjt** [gophercises/quiz#20]
The weblink for problem.csv on Quiz points to Quiz exercise main page instead of CSV file download.

![screenshot from 2018-03-31 01-39-52](https://user-images.githubusercontent.com/10371494/38152293-bf99a14e-3484-11e8-88e5-230100ec21e2.png)

Please fix.

**Comment by joncalhoun** [comment]
While not the most ideal solution, this was quick and seems good enough for now since the contents of `problem.csv` are shown in the README already.
