### ISSUE TITLE
Handle wrong answers

### ISSUE THREAD

**Issue by veganexe** [gophercises/quiz#25]
Let's take @csos95 's implementation. Suppose one question is answered wrong. How to add that question BACK to the range, so it can be asked again later?

**Comment by joncalhoun** [comment]
There are a few ways you could do this. One would be to add the question to the back of the slice of questions and to update the for loop that iterates over all questions to check its length every pass. Do you have a need for this? If you have some code where you are trying you can post it and I'll try to help out.

**Comment by veganexe** [comment]
Yes, using it myself for language learning. Revising the answers i have gotten wrong would help alot! I am currently using csos95’s implementation. Only thing i have changed is removing the time limit flag and channel.

I did make an attempt at this before. But all I could come up with is to print the wrong ones at the end of the quiz using bytes.Buffer.

But adding the adding them back to the slice would be more.... intuitive.

**Comment by veganexe** [comment]
```package main

import (
	"encoding/csv"
	"flag"
	"fmt"
	"log"
	"math/rand"
	"os"
	"os/exec"
	"runtime"
	"time"

	"github.com/fatih/color"
)

var (
	flagNoColor = flag.Bool("no-color", false, "disable color output")
	csvPath = flag.String("src", "src.csv", "source")
	lang = flag.String("lang", "random", "language")
	num = flag.Int("n", -1, "number")
)

var clear map[string]func()

func init() {
	clear = make(map[string]func())
		clear["linux"] = func() {
		cmd := exec.Command("clear")
		cmd.Stdout = os.Stdout
		cmd.Run()
	}
	clear["windows"] = func() {
		cmd := exec.Command("cmd", "/c", "cls")
		cmd.Stdout = os.Stdout
		cmd.Run()
	}
}

func CallClear() {
	value, ok := clear[runtime.GOOS]
	if ok {
		value()
	} else {
		panic("Panic!")
	}
}

func random(min int, max int) int {
	return rand.Intn((max-min) + 1) + min
}

func main() {

	flag.Parse()

	file, err := os.Open(*csvPath)
	if err != nil {
		log.Println(err)
		return
	}
	defer file.Close()

	csvReader := csv.NewReader(file)

	csvData, err := csvReader.ReadAll()
	if err != nil {
		log.Println(err)
		return
	}

	qaPair := make(map[string]string, len(csvData))
	for _, data := range csvData {
		qaPair[data[0]] = data[1]
	}

	done := make(chan bool)
	breakF := make(chan bool)

	qNum := 0

	go func() {
		if *flagNoColor {
			color.NoColor = true
		}
		white := color.New(color.FgWhite)
		boldWhite := white.Add(color.Bold)

		for one, two := range qaPair {
			if qNum == *num {
				breakF <- true
			}
			rand.Seed(time.Now().UnixNano())
			randomNum := random(1, 2)
			CallClear()
			if *lang == "es" {
				randomNum = 1
			} else if *lang == "en" {
				randomNum = 2
			}
			qNum++
			boldWhite.Printf("\n #   %d / %d\n", qNum, len(qaPair))
			if randomNum == 1 {
				boldWhite.Printf("\n Q   %s", one)
				fmt.Scanln()
				boldWhite.Printf("\n A   %s", two)
				fmt.Scanln()
			} else {
				boldWhite.Printf("\n Q   %s", two)
				fmt.Scanln()
				boldWhite.Printf("\n A   %s", one)
				fmt.Scanln()
			}
			CallClear()
		}
		done <- true
	}()

	select {
		case <-done:
		case <-breakF:
	}

}```

@joncalhoun

**Comment by veganexe** [comment]
I added a `-n` limit which limits the number of questions asked. This would make adding back questions more tricky cuz it might get added to the slice but not the `n` questions asked in the session. Need your help.

P.S there is no answer validation as I don't require that

**Comment by csos95** [comment]
In my implementation I use a map to store the question and answer pairs.  
This gives me a randomized ordering when I range over them, but also means that new items can't simply be added inside the loop because there is no guarantee they would be ranged over.  
To re-ask incorrect questions I would add incorrect questions to a second map, swap the qaPair map with this second map, and loop over the part that asks questions until the qaPair map is empty.  

```
// loop until the map is empty
for len(qaPair) != 0 {
	// a second map to store incorrect questions
	qaPairIncorrect := make(map[string]string, 0)
	// iteration order for maps in go is randomized so the questions won't be in the same order every time
	for question, answer := range qaPair {
		qNum++
		// ask a question
		fmt.Printf("Problem #%d: %s = ", qNum, question)
		// get an answer
		scanner.Scan()
		userAnswer = scanner.Text()
		// trim leading and trailing whitespace
		userAnswer = strings.TrimSpace(userAnswer)
		userAnswer = strings.ToLower(userAnswer)
		answer = strings.ToLower(answer)
		// check the answer
		if answer == userAnswer {
			numCorrect++
		} else {
			// if it was incorrect, add it to the second map
			qaPairIncorrect[question] = answer
		}
	}
	// replace the first map with the second
	qaPair = qaPairIncorrect
}
```

This breaks the last print statement showing the score so I would also change the last argument from `len(qaPair)` to `qNum`

**Comment by joncalhoun** [comment]
@csos95 Thanks for chiming in 👍 

@veganexe if you need more help let me know, but it looks like the code sample Christopher gave should help get you going 😄
